### ISSUE TITLE
ImportError: This module is deprecated.  Use tf.nn.rnn_* instead.

### ISSUE THREAD

**Issue by northanapon** [crazydonkey200/tensorflow-char-rnn#1]
The error occurred when testing the source code:

``` shell
python train.py --data_file=data/tiny_shakespeare.txt --num_epochs=10 --test
```

Here is the full stack:

``` python
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    from char_rnn_model import *
  File "/websail/nor/tf/tensorflow-char-rnn/char_rnn_model.py", line 5, in <module>
    from tensorflow.models.rnn import rnn
  File "/home/northanapon/.virtualenvs/tf/lib/python2.7/site-packages/tensorflow/models/rnn/rnn.py", line 21, in <module>
    raise ImportError("This module is deprecated.  Use tf.nn.rnn_* instead.")
ImportError: This module is deprecated.  Use tf.nn.rnn_* instead.
```

I am using GPU version of Tensorflow `0.9.0rc0`.

**Comment by crazydonkey200** [comment]
Thanks. Just fixed the problem.

**Comment by fighting41love** [comment]
Same error. How to fix the problem?

**Comment by northanapon** [comment]
Are you sure that the same error? This was solved for long time ago. If it is related to state tuple, you should check out this pull request: https://github.com/crazydonkey200/tensorflow-char-rnn/pull/2.

**Comment by fighting41love** [comment]
Thanks for your response. @NorThanapon 
Problem solved by modifying some codes.
The codes I run are written with previous version of tensorflow.
However,  I used another version to run the code which caused the error.
Thanks!
