### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201d' in position 4066: ordinal not in range(128)

### ISSUE THREAD

**Issue by oxmah** [crazydonkey200/tensorflow-char-rnn#11]
Hello !

First, thanks for your great work !

I would like to export sample directly into files by using ">>" but I'm encountering this error. Any idea where it comes from ?

**Comment by oxmah** [comment]
Fixed !

I changed 

`print('Sampled text is:\n%s' % sample)`

to

`print('Sampled text is:\n%s' % sample.encode('ascii', 'ignore').decode('ascii'))`


in sample.py line 111

**Comment by crazydonkey200** [comment]
Cool. Sometimes people want to use the code with other encodings like "GB2312" for text in other languages. I guess a more general approach is to use the same encoding for sampled text as the training text.
