### ISSUE TITLE
Parameters

### ISSUE THREAD

**Issue by xslittlegrass** [crazydonkey200/tensorflow-char-rnn#13]
Thanks for sharing!
Do you have the parameters to reproduce the results in karpathy's blog, for instance the latex example and the linux source code example?

**Comment by crazydonkey200** [comment]
Hi, I don't have the exact parameters, but I tried the linux source code with the default parameters, and the result looks reasonable. I suggest to have a try to see if the result makes sense :)

**Comment by crazydonkey200** [comment]
Feel free to reopen if you want to discuss more about replicating Karpathy's result.
