### ISSUE TITLE
How to know how confident the model is about a sample it generated?

### ISSUE THREAD

**Issue by ghost** [crazydonkey200/tensorflow-char-rnn#14]
Hi! I'm a newbie in neural networks. So pardon me if I'm asking stupid questions. 

Is there a way to know how confident the model is about a sample it generated? 
I mean, for example, when max_prob is FALSE, if we run sample.py for several times, the model would generate several different samples. For each sample it generated, the model might have different confidence in the sample. 
So, how to measure the confidence about a particular sample it generated?
Can the model produce something like a confidence score?
Or, what variable should I be looking that already reveals this confidence?

Maybe it's easier to calculate the confidence if we set max_prob to TRUE, and every time we get the same sample? and still, how to calculate the confidence in that case?

I'm not sure if I expressed it right. Please let me know if I'm not clear enough. 
Many thanks! :)

**Comment by crazydonkey200** [comment]
Hi, you can compute the probability of a given sample as the product of the probabilities for generating each character. So the probability for generating "cat" would be P(\<start-of-sentence\>) * P("c" | \<start-of-sentence\>) * P("a"|"c") * P("t" | "ca"). This is related to the [perplexity](https://en.wikipedia.org/wiki/Perplexity) which are usually used for evaluating language models. Roughly speaking, the lower the perplexity of a sample, the higher the confidence a model has for it. 

The "sample.py" code supports computing the perplexity of a given text using the argument "--evaluate". You can look into the code 
[here](https://github.com/crazydonkey200/tensorflow-char-rnn/blob/master/sample.py#L90) for more information.

**Comment by ghost** [comment]
Hi Chen, many thanks for the detailed answer! 
I hope you don't mind me asking further. 
I noticed that the argument "--evaluate" doesn't take in a start_text or generate new characters.
In my case, if I want to feed into the model a start_text and let the model generate the next characters and produce the confidence at the same time, what should I do?
For example, in sampling, if I want to feed into the model a sentence like "Knock, knock. " as a start text, and see what the model generate as a reply to that start text, and produce the confidence score (or perplexity) at the same time, how should I do it?
In this case, if the model is trained well with lots of Knock Knock jokes, then as an ideal reply, the model should generate "Who's there?" in the next characters in the sample, then I should see a high confidence score (or low perplexity), or maybe the model will generate something else and I see a different confidence with the different samples it generated. Either way, I'm curious to let the model generate replies to a start text and see how confident it is about the replies.

**Comment by crazydonkey200** [comment]
Hi Sara, I think what you can do is to first sample from the trained model using "--start_text" to generate new text. Then feed in the generated text using "--example_text" with "--evaluate" to compute its perplexity.

**Comment by crazydonkey200** [comment]
Issue closed since the problem seems to be resolved.
