### ISSUE TITLE
Is num_unrollings the same as seq_length in the original char-rnn?

### ISSUE THREAD

**Issue by jamesqo** [crazydonkey200/tensorflow-char-rnn#22]
Hi, I'm not really familiar with much of the ML terminology yet. Just to clarify, is the `num_unrollings` parameter used in the same way as `seq_length` is in the original repo? Also, why does it default to 10 instead of 50 (like [here](https://github.com/karpathy/char-rnn/blob/6f9487a6fe5b420b7ca9afb0d7c078e37c1d1b4e/train.lua#L47))? Thanks

**Comment by crazydonkey200** [comment]
Hi, Yes, `num_unrollings` is the same as `seq_length`. Generally, larger `num_unrollings` can capture longer dependencies in the text, but it takes longer to train. I used 10 for faster training here, but you could change it as a commandline argument.
