### ISSUE TITLE
Output activations of individual neurons of a given layer of a trained model.

### ISSUE THREAD

**Issue by tlhumphrey2** [crazydonkey200/tensorflow-char-rnn#8]
I want to see what the activations are for individual neurons of a given layer for a given input character.

Any suggestions?

**Comment by crazydonkey200** [comment]
The problem is that the current TensorFlow API for RNN doesn't expose the hidden activations. You probably need to create a customized RNN cell to add hidden activations into the output.

**Comment by crazydonkey200** [comment]
Close for now. You could reopen it when there are further questions.
